openapi: 3.0.0
info:
  title: TaskApp
  description: Task notes app
  version: 0.0.1
tags:
  - name: "Task"
    description: "Tasks list"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
